name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start Backend
      run: npm run start-be &
    - name: Start Frontend
      run: npm run start-fe &
    - name: Install Browsers
      run: npx playwright install
    - name: Run UI Tests
      run: npm run test:ui

  deploy-be:

    runs-on: ubuntu-latest
    needs: build_test

    steps:
        - name: Checkout the repo 
          uses: actions/checkout@v3
        - name: Deploy BackEnd
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_KEY }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true 
    
  deploy-fe:

    runs-on: ubuntu-latest
    needs: build_test

    steps:
        - name: Checkout the repo
          uses: actions/checkout@v3
        - name: Deploy FrontEnd
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_KEY }}
            api_key: ${{ secrets.MY_RENDER_SEVICE_KEY_FE }}
            wait_deploy: true 
