name: Build, Test, Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repo on the machine
      uses: actions/checkout@v4

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Run npm security tests
      run: npm audit

  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repo on the machine
      uses: actions/checkout@v4

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install required system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2t64 libnss3 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxcursor1 \
          libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libgbm1 libglib2.0-0 \
          libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libgtk-3-0 \
          libpango-1.0-0 libwayland-client0 libwayland-egl1 libwayland-server0 libxkbcommon0 \
          libffi8 libicu-dev libx264-164
    
    

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

  deploy:
    runs-on: ubuntu-latest
    needs: [ "build_test", "security_tests" ]

    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_KEY }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

