name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Start Backend
      run: npm run start-be &
    - name: Start Frontend
      run: npm run start-fe &
    - name: Install Browsers
      run: npx playwright install
    - name: Run UI Tests
      run: npm run test:ui

  # deploy:

  #   runs-on: ubuntu-latest
  #   needs: build_test

  #   steps:
  #       - uses: actions/checkout@v3
  #       - uses: JorgeLNJunior/render-deploy@v1.4.4
  #         with:
  #           service_id: ${{ secrets.MY_RENDER_SERVICE_KEY }}
  #           api_key: ${{ secrets.MY_RENDER_API_KEY }}
  #           wait_deploy: true 
